#!/usr/bin/env bash
# internal/version/version.go is gitignored and regenerated by this script
# on every build; a bare `go build`/`go test` without going through `make`
# first will fail to compile.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

version="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"

mkdir -p internal/version
cat > internal/version/version.go <<EOF
// Code generated by scripts/generate-version.sh. DO NOT EDIT.
package version

const Version = "$version"
EOF
