#!/usr/bin/env bash
# Writes internal/version/version.go from the current git state. Run via
# `make generate-version` (a prerequisite of build/test/vet/image) — never
# committed, mirrors how pki/out/ is generated-and-gitignored.
#
# On a clean, exactly-tagged commit this is just the tag (e.g. v1.2.3),
# which is exactly what `make release` needs — see scripts/release.sh.
# Otherwise it's git describe's usual "<tag>-<distance>-g<sha>[-dirty]"
# form, still informative for ordinary dev builds.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

version="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"

mkdir -p internal/version
cat > internal/version/version.go <<EOF
// Code generated by scripts/generate-version.sh. DO NOT EDIT.
package version

// Version is this build's version, derived from the nearest git tag.
const Version = "$version"
EOF
